const fs = require('fs')

const kebabCaseToCamelCase = (str: string) => str.replace(/-([a-z])/g, g => g[1].toUpperCase())

let toImport = '/** THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. **/\n\n'

const folders = fs.readdirSync('./src/runtime/components').filter((f: string) => f !== 'index.ts')
const names = []
for (const component of (folders || [])) {
  const name = kebabCaseToCamelCase(component)
  toImport += `import ${name} from './${component}/index.vue'\n`
  names.push(name)
}
toImport += `\ninterface components {
  [key: string]: Object
}\n`
toImport += `\nexport default {\n  ${names.join(',\n  ')}\n} as components`

fs.writeFileSync('./src/runtime/components/index.ts', toImport.trim() + '\n')
