name: Bump version
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Standard Version
        uses: qzb/standard-version-action@v1.0.7
#      - name: NPM Publish
#        uses: JS-DevTools/npm-publish@v1
#        with:
#          token: ${{ secrets.NPM_TOKEN }}
