name: Bump version
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        if: steps.changes.outputs.src == 'true'
        uses: actions/checkout@v3

      - name: Configure committer
        if: steps.changes.outputs.src == 'true'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Bump version
        if: steps.changes.outputs.src == 'true'
        uses: qzb/standard-version-action@v1.0.7

      - name: Push bump
        if: steps.changes.outputs.src == 'true'
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git push --follow-tags origin main

      - name: Publish version
        if: steps.changes.outputs.src == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
